/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formulario;

import javax.swing.JOptionPane;
import Conexion.CreateConection;
//librerias para manipular datos
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author Lorenzo1
 */
public class Empleado extends javax.swing.JFrame {
    CreateConection conexionPostgres = new CreateConection();
    Connection con;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Empleado.class.getName());

    /**
     * Creates new form Cliente
     */
    public Empleado() throws SQLException {
        initComponents();
        con = conexionPostgres.getConection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtid = new javax.swing.JLabel();
        jtxtNombew = new javax.swing.JLabel();
        jtxtApellido = new javax.swing.JLabel();
        jtxtSalario = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtSalario = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtxtid.setText("Id");

        jtxtNombew.setText("Nombre");

        jtxtApellido.setText("Apellido");

        jtxtSalario.setText("Salario");

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtApellido)
                    .addComponent(jtxtNombew)
                    .addComponent(jtxtid, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtSalario, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(txtNombre)
                    .addComponent(txtApellido)
                    .addComponent(txtSalario))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtid)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtNombew)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtApellido)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtSalario)
                    .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void guardarEmpleado(){
                try{
            // Estraigo los valores que tiene en la interfaz de lo JText
            String nombre = txtNombre.getText();
            String apellido = txtApellido.getText();
            String salario = txtSalario.getText();
            //Espacio de trabajo que lleba la conexion para escribir setencias sql
          Statement smt = con.createStatement();
          // es mi Setencia
          String qry = "insert into public.empleado(nombre,apellido,salario)"
                  + "values('"+nombre+"','"+apellido+"',"+salario+")";
          int filasInsertadas = smt.executeUpdate(qry);
          //Ejecuta la setencia a la base de datos, la cual retorna un int
          JOptionPane.showMessageDialog(null, "Taotal de Registros insertados" +filasInsertadas);
          smt.close();
        } catch (SQLException e){
                    e.getMessage();
                    }
    }
    public void guardarEmpleadoPS(){
                try{
            // Estraigo los valores que tiene en la interfaz de lo JText
            String nombre = txtNombre.getText();
            String apellido = txtApellido.getText();
            String salario = txtSalario.getText();
          // es mi Setencia
          String qry = "insert into public.empleado(nombre,apellido,salario)"
                  + "values(?,?,?)";
            //Espacio de trabajo que lleba la conexion para escribir setencias sql
          PreparedStatement ps = con.prepareStatement(qry);
          ps.setString(1,nombre);
          ps.setString(2,apellido);
          ps.setDouble(3, Double.parseDouble(salario));

          int filasInsertadas = ps.executeUpdate(qry);
          //Ejecuta la setencia a la base de datos, la cual retorna un int
          JOptionPane.showMessageDialog(null, "Total de Registros insertados" +filasInsertadas);
          ps.close();
        } catch (SQLException e){
                    e.getMessage();
                    }
    }
        public void getEmpleado(int id){
          try{
          String qry = "select id,nombre,apellido,salario from public.empleado where id = ?";
          PreparedStatement ps = con.prepareStatement(qry);
          ps.setInt(1,id);
          ResultSet rs = ps.executeQuery(qry);
          while (rs.next()){
              txtNombre.setText(rs.getString("nombre"));
              txtApellido.setText(rs.getString("apellido"));
              txtSalario.setText(rs.getString("salario"));
              //txtId.setText(rs.getString("id"));
          }
          ps.close();
        } catch (SQLException e){
                    e.getMessage();
                    }

}
    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        getEmpleado(id);
    }//GEN-LAST:event_btnConsultarActionPerformed

        
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        try{
          String qry = "delete from public.empleado where id = ?";
          String id=JOptionPane.showInputDialog("Ingrese el codigo a eliminar");
          PreparedStatement ps = con.prepareStatement(qry);
          ps.setInt(1,Integer.parseInt(id));
          int filasEliminadas = ps.executeUpdate();
          JOptionPane.showMessageDialog(null, "Total de registros eliminados" +filasEliminadas);
          ps.close();
        } catch (SQLException e){
                    e.getMessage();
                    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        guardarEmpleado();
                // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Empleado().setVisible(true);
            } catch (SQLException ex) {
                System.getLogger(Empleado.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jtxtApellido;
    private javax.swing.JLabel jtxtNombew;
    private javax.swing.JLabel jtxtSalario;
    private javax.swing.JLabel jtxtid;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSalario;
    // End of variables declaration//GEN-END:variables
}
